### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by jugendhacker** [DevMountain/soundCloud-api#5]
There is now way to get a API key at the moment, right?

**Comment by phanirithvij2000** [comment]
@jugendhacker 
Yeah
Did you try using this key given by Devmountain ?

**Comment by jugendhacker** [comment]
@phanirithvij2000 I don't, because I want my own key!

**Comment by phanirithvij2000** [comment]
Inspect the requests on SoundCloud and you'll be able to know your client id

It is also an API key

**Comment by jugendhacker** [comment]
@phanirithvij2000 really?

**Comment by phanirithvij2000** [comment]
Yeah.
It's not fully functional but
You will be able to access some API methods

I will post some code here after some time

**Comment by phanirithvij** [comment]
## To get your client_id

Just inspect the requests going out in the browser, almost all of them are XHR.
So, go to `Developer Tools -> Network -> XHR`, You'll find API request urls of format

```
https://api.soundcloud.com/i1/tracks/{SOME_ID}/streams?client_id={YOUR_CLIENT_ID}
or
https://api-v2.soundcloud.com/users/soundcloud:users:{YOUR_USER_ID}/stats/totals/plays?client_id={YOUR_CLIENT_ID}&from=1531144800000&to=1531227600000&app_version=1530785013&app_locale=en
```

### Once you have your _**client\_id**_

```python3
# Usage: client = login()
def login():
   return soundcloud.Client(
      client_id='client_id',
      username="soundcloud_username",
      password="password"
)
client = login()
url = "https://soundcloud.com/strangefruitsmusic/sf006" #ANY SOUNCLOUD TRACK URL
# resolve track URL into track resource
track = client.get('/resolve', url=url)
track_details = track.fields()
comment_details = []
for comment in client.get('/tracks/%d/comments' % track.id):
    comment_details.append(comment.fields())
data = client.get("/tracks/%d/streams" % track.id)
data_details = data.fields()
print(track_details)
print({"data":data_details, "track":track_details, "comments":comment_details})
```

**Comment by jugendhacker** [comment]
@phanirithvij but I think this isnt very legal...

**Comment by phanirithvij** [comment]
Well I think don't so

We **won't** get the full functions of the api **the souncloud team has designed**, by using this method.

## And we are passing our legal account credentials so I'm sure this is just like logging in.

What we're doing becomes Illegal when we

Distribute the content or use it in a commercial way

**Comment by phanirithvij** [comment]
It all depends on your purpose

### If you wan't to get the data for yourself <----- NOT ILLEGAL

### If you want to embed the track <------ ABSOLUTELY LEGAL (THEY PROVIDE IT)

**Comment by jugendhacker** [comment]
But if I want to develope my own application it's illegal, and please stop writing with headers/highlights, it's difficult to read something like your messages...

**Comment by phanirithvij** [comment]
Illegal it is
I'm sorry about my way of explanation

**Comment by jugendhacker** [comment]
Ok but I want to develope my own application and that for I need a key, I also asked in the SC Forum but no one really answered...
